module.exports = {
  AddReactions: "新增反應",
  Administrator: "管理者",
  AttachFiles: "附加檔案",
  BanMembers: "對成員停權",
  ChangeNickname: "更改暱稱",
  Connect: "連接",
  CreateInstantInvite: "建立邀請",
  CreatePrivateThreads: "建立公開討論串",
  CreatePublicThreads: "建立私人討論串",
  DeafenMembers: "讓成員拒聽",
  EmbedLinks: "嵌入連結",
  KickMembers: "踢出成員",
  ManageChannels: "管理頻道",
  ManageEmojisAndStickers: "管理表情符號或貼圖",
  ManageEvents: "管理活動",
  ManageGuild: "管理伺服器",
  ManageMessages: "管理訊息",
  ManageNicknames: "感裡暱稱",
  ManageRoles: "管理身份組",
  ManageThreads: "管理討埨串",
  ManageWebhooks: "管理 webhooks",
  MentionEveryone: "提及 everyone",
  ModerateMembers: "處分成員",
  MoveMembers: "移動成員",
  MuteMembers: "將成員靜音",
  PrioritySpeaker: "優先發言者",
  ReadMessageHistory: "讀取訊息裡使",
  RequestToSpeak: "請求發言",
  SendMessages: "發送訊息",
  SendMessagesInThreads: "在討論串中傳送訊息",
  SendTTSMessages: "傳送 TTS 訊息",
  Speak: "說話",
  Stream: "欲訊通話",
  UseApplicationCommands: "使用應用程式命令",
  UseEmbeddedActivities: "嵌入連結",
  UseExternalEmojis: "使用外部表情符號",
  UseExternalStickers: "使用外部貼圖",
  UseVAD: "使用語音活動",
  ViewAuditLog: "檢視審核紀錄",
  ViewChannel: "檢視頻道",
  ViewGuildInsights: "查看伺服器分析",
};
